targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-apple-darwin" },
]

[bans]
multiple-versions = "deny"
deny = [
    # See: https://github.com/rust-random/rand/issues/645
    { name = "rand", version = "<0.6" },

    # See: https://github.com/near/nearcore/pull/3595
    { name = "ethabi", version = "<9.0.1" },
    { name = "ethabi-contract", version = "<9.0.0" },
    { name = "ethabi-derive", version = "<9.0.1" },
    { name = "ethereum-types", version = "<0.8.0" },
    { name = "keccak-hash", version = "<0.4.1" },
    { name = "primitive-types", version = "<0.6.2" },
    { name = "uint", version = "<0.8.2" },
]

skip = [
    # crypto-mac 0.7.0 still uses it: https://github.com/RustCrypto/traits/issues/43
    { name = "subtle", version = "=1.0.0" },

    # wabt 0.9.0 (dev dependency) still uses it
    { name = "glob", version = "=0.2.11" },

    # near-epoch-manager fixed the rand version to ensure protocol stability
    { name = "rand", version = "=0.6.5" },
    # rand 0.6.5 uses two versions of rand_core due to weird dependencies mismatch with rand_chacha
    { name = "rand_core", version = "=0.3.1" },
    { name = "rand_chacha", version = "=0.1.1" },
    { name = "autocfg", version = "=0.1.7" },
    # wasmer 0.17 and wasmtime 0.17 use conflicting versions of those
    { name = "base64", version = "=0.11.0" },
    { name = "wasmparser", version = "=0.51.4" },
    { name = "rand_core", version = "=0.4.2" },
    # wasmer 0.17 and wasmtime 0.17 uses older versions of some crates
    { name = "sha2", version = "=0.8.2" },
    { name = "crypto-mac", version = "=0.7.0" },
    { name = "block-padding", version = "=0.1.5" },
    { name = "block-buffer", version = "=0.7.3" },
    { name = "opaque-debug", version = "=0.2.3" },
    { name = "generic-array", version = "=0.12.3" },

    # `sha2` uses it
    { name = "cfg-if", version = "=1.0.0" },

    # evm support has some legacy. Updating it fails at this point.
    # to fully update, need to fork half of parity libraries, as they stopped development.
    # See: https://github.com/near/nearcore/issues/3506
    { name = "digest", version = "=0.8.1" },
    { name = "elastic-array", version = "=0.10.3" },
    { name = "impl-serde", version = "=0.2.3" },
    { name = "parking_lot_core", version = "=0.6.2" },
    { name = "proc-macro2", version = "=0.4.30" },
    { name = "quote", version = "=0.6.13" },
    { name = "rustc-hex", version = "=1.0.0" },
    { name = "syn", version = "=0.15.44" },
    { name = "unicode-xid", version = "=0.1.0" },
    { name = "primitive-types", version = "=0.6.2" },
    { name = "fixed-hash", version = "=0.5.2" },

    # param estimator uses newer imports, but it's not part of neard
    { name = "indicatif", version = "=0.15.0" },
    { name = "rand_xorshift", version = "=0.2.0" },
    { name = "wasmparser", version = "=0.59.0" },

    # wasmtime and actix-http
    { name = "gimli", version = "=0.23.0" },

    # actix-http's deps backtrace and flate2 use different versions
    { name = "miniz_oxide", version = "=0.4.3" },
   
    # wasmer and wasmtime
    { name = "target-lexicon", version = "=0.11.1" },

    # actix-http and actix
    { name = "pin-project", version = "=0.4.27" },

    # chain and param estimator
    { name = "num-rational", version = "=0.3.2" },

    # tokia via actix and actix-server
    { name = "miow", version = "=0.3.6" },

    # crossbeam-epoch and wasmtime-runtime
    { name = "memoffset", version = "=0.6.1" },

    # rayon-core and actix
    { name = "crossbeam-utils",  version = "=0.8.1"},
    
    # tracing-subscriber via near-logger-utils and clap via bindgen
    { name = "ansi_term", version = "=0.12.1" },

    # trie-db via patricia-trie-ethereum and indexmap via actix-http
    { name = "hashbrown", version = "=0.6.3" },

    # wasmer 0.17.x
    { name = "parking_lot", version = "=0.9.0" },
    { name = "parking_lot", version = "=0.10.2" },
    { name = "parking_lot_core", version = "=0.7.2" },
    { name = "lock_api", version = "=0.3.4" },
    { name = "smallvec", version = "0.6.14" },

    # ethereum-types via old evm (openethereum)
    { name = "uint", version = "=0.8.5" },
    { name = "tiny-keccak", version = "=1.5.0" },
    { name = "rlp", version = "=0.4.6" },
    { name = "impl-rlp", version = "=0.2.1" },
    { name = "impl-codec", version = "=0.4.2" },
    { name = "radium", version = "0.3.0" },
    { name = "primitive-types", version = "0.8.0" },
    { name = "parity-scale-codec", version = "1.3.6" },
    { name = "bitvec", version = "=0.17.4" },
    { name = "byte-slice-cast", version = "=0.3.5" },
    { name = "keccak-hash", version = "0.4.1" },
    { name = "ethereum-types", version = "=0.8.0" },
    { name = "ethereum-types", version = "=0.10.0" },
    { name = "ethbloom", version = "=0.8.1" },
    { name = "ethbloom", version = "=0.10.0" },

    # wasmtime uses older dependencies
    { name = "object", version = "0.21.1" },

    # chrono uses old time crate
    { name = "time", version = "=0.1.43" },

    # clap v2 uses old versions
    { name = "strsim", version = "0.8.0" },

    # ed25519-dalek uses older versions of rand and rand_core
    { name = "rand", version = "=0.7.3" },
    { name = "rand_core", version = "=0.5.1" },
    { name = "rand_chacha", version = "=0.2.2" },
    { name = "getrandom", version = "=0.1.16" },

    # h2 uses older tracing-futures
    { name = "pin-project-internal", version = "0.4.27" },

    # criterion and criterion-plot use conflicting versions
    { name = "itertools", version = "=0.9.0" },

    # actix 0.11 and actix-rt 2.0 use conflicting versions
    { name = "actix-macros", version = "=0.1.3" },

    # hashbrown uses an older version
    { name = "ahash", version = "=0.4.7" },
]
